EXTRA_CFLAGS += -Idrivers/staging/tegra/include

obj-$(CONFIG_TEGRA_DOWNSTREAM) += video/
obj-$(CONFIG_TEGRA_DOWNSTREAM) += csi.o
obj-$(CONFIG_TEGRA_DOWNSTREAM) += clk.o
obj-$(CONFIG_TEGRA_DOWNSTREAM) += pageattr.o
obj-$(CONFIG_TEGRA_DOWNSTREAM) += powergate.o
