GCOV_PROFILE := y
EXTRA_CFLAGS += -Idrivers/staging/tegra/video/host
EXTRA_CFLAGS += -Idrivers/staging/tegra/include
obj-y += dev.o
obj-y += util.o
obj-y += cursor.o
obj-y += events.o
obj-y += control.o
