EXTRA_CFLAGS += -Idrivers/staging/tegra/include
EXTRA_CFLAGS += -Idrivers/staging/tegra/video/host

obj-$(CONFIG_VIDEO_TEGRA_V4L) += tegra_v4l2_camera.o
obj-$(CONFIG_VIDEO_TEGRA_V4L) += videobuf2-dma-nvmap.o
